### ISSUE TITLE
Add default submit args for resource_manager?

### ISSUE THREAD

**Issue by nickjer** [OSC/ood_appkit#18]
Should we rely on the batch server's and `qsub`'s list of default submission arguments, or manually specify them in the configuration yaml?

For example, defaults when submitting `qsub` without arguments **seem** to be equivalent to:

- oakley: `-N STDIN -l nodes=1:ppn=1 -l walltime=01:00:00`
- ruby: `-N STDIN -l nodes=1:ppn=1 -l walltime=01:00:00`
- quick: `-N STDIN -l nodes=1:ppn=1:ruby -l walltime=01:00:00`

Maybe those are perfectly fine for us and this feature is unnecessary. Or maybe we add this feature but rely on system defaults if this is unspecified in the yaml.

The yaml would look like:

```yaml

v1:
  oakley:
    title: 'Oakley'
    servers:
      login:
        type: 'OodAppkit::Server'
        host: 'oakley.osc.edu'
      resource_mgr:
        type: 'OodAppkit::Servers::Torque'
        host: 'oak-batch.osc.edu'
        prefix: '/usr/local/torque/5.1.1-1_fba25d92'
        version: '5.1.1'
        default_submit_args:
          headers:
            Job_Name: 'NamelessOodApp'
          resources:
            nodes: '1:ppn=12'
            walltime: '01:00:00'
      ..
    ...
```

As I said, this may be unnecessary. Just something to think about.
